---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name}}-persistent-volume
  labels:
    app: {{ .Chart.Name}}
spec:
  capacity:
    storage: {{ .Values.storagesize}}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - eastus
