---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name}}-secret
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Chart.Name}}
type: Opaque
data:
  db-password: {database-password}
  nxrm-admin-password: {nexus-login-password}
