---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name}}-persistent-volume-claim
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Chart.Name}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Chart.Name }}-storage-class
  volumeName: {{ .Chart.Name}}-persistent-volume
  resources:
    requests:
      storage: {{ .Values.storagesize}}